port: /dev/dashgo
baud: 115200
timeout: 0.1

use_base_controller: True
base_controller_rate: 20

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_link
publish_tf: false

# === Robot drivetrain parameters
wheel_diameter: 0.162
wheel_track: 0.392
encoder_resolution: 915
gear_reduction: 1.0
motors_reversed: False

# === PID parameters
Kp: 40
Kd: 25
Ki: 0
Ko: 50
accel_limit: 0.01
decel_limit: 0.05
